# Generated by Django 2.2 on 2021-07-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20210722_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dojo',
        ),
    ]
